version: '3'
services:
    sqlserver:
      image: microsoft/mssql-server-linux
      hostname: db1
      container_name: sqlserver_bookstore
      environment:
         SA_PASSWORD: "MssqlPass123"
         ACCEPT_EULA: "Y"
         MSSQL_SA_PASSWORD: "DockerSql2017!"
         MSSQL_PID: "Developer"
      ports:
        - "11433:1433"